"""add_events

Revision ID: 0002_add_events
Revises: 0001_initial
Create Date: 2024-01-02 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002_add_events'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    event_status = postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='eventstatus')
    event_status.create(op.get_bind(), checkfirst=True)
    
    event_category = postgresql.ENUM('ART', 'MUSIC', 'THEATER', 'LITERATURE', 'CINEMA', 'DANCE', 'OTHER', name='eventcategory')
    event_category.create(op.get_bind(), checkfirst=True)
    
    event_region = postgresql.ENUM('METROPOLITANA', 'VALPARAISO', 'BIOBIO', 'ONLINE', name='eventregion')
    event_region.create(op.get_bind(), checkfirst=True)

    op.create_table('event',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', postgresql.ENUM('ART', 'MUSIC', 'THEATER', 'LITERATURE', 'CINEMA', 'DANCE', 'OTHER', name='eventcategory', create_type=False), nullable=False),
    sa.Column('region', postgresql.ENUM('METROPOLITANA', 'VALPARAISO', 'BIOBIO', 'ONLINE', name='eventregion', create_type=False), nullable=False),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='eventstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_category'), 'event', ['category'], unique=False)
    op.create_index(op.f('ix_event_region'), 'event', ['region'], unique=False)
    op.create_index(op.f('ix_event_slug'), 'event', ['slug'], unique=True)
    op.create_index(op.f('ix_event_status'), 'event', ['status'], unique=False)
    op.create_index(op.f('ix_event_title'), 'event', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index(op.f('ix_event_title'), table_name='event')
    op.drop_index(op.f('ix_event_status'), table_name='event')
    op.drop_index(op.f('ix_event_slug'), table_name='event')
    op.drop_index(op.f('ix_event_region'), table_name='event')
    op.drop_index(op.f('ix_event_category'), table_name='event')
    op.drop_table('event')
    
    sa.Enum(name='eventstatus').drop(op.get_bind())
    sa.Enum(name='eventcategory').drop(op.get_bind())
    sa.Enum(name='eventregion').drop(op.get_bind())
    # ### end Alembic commands ###
