"""add_newsletter

Revision ID: 0003_add_newsletter
Revises: 0002_add_events
Create Date: 2024-01-03 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003_add_newsletter'
down_revision: Union[str, None] = '0002_add_events'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    newsletter_status = postgresql.ENUM('DRAFT', 'SENDING', 'SENT', 'FAILED', name='newsletterstatus')
    newsletter_status.create(op.get_bind())
    
    op.create_table('newsletter',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENDING', 'SENT', 'FAILED', name='newsletterstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_status'), 'newsletter', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index(op.f('ix_newsletter_status'), table_name='newsletter')
    op.drop_table('newsletter')
    sa.Enum(name='newsletterstatus').drop(op.get_bind())
    # ### end Alembic commands ###
